# Web服务器配置
server:
  port: 8081
spring:
  application:
    name: ipc-server
  datasource:
    url: jdbc:mysql://localhost:3306/ipc?useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 2yatou1314
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

# mybatis-plus相关配置
mybatis-plus:
  typeAliasesPackage: com.ipc.server.entity
  global-config:
    db-config:
      logic-delete-field: deleted  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

#FFmpeg配置
ffmpeg:
  path: ffmpeg
  launchThreadSize: 5

#流服务器配置
streaming:
  server:
    # nginx，rtmp配置
    pushEndpoint: rtmp://192.168.213.128:1935/mylive/
    # nginx，http-flv配置   ?app=live&stream=
    pullEndpoint: http://192.168.213.128/live?app=mylive&stream=
    # nginx stat配置
    flvStatEndpoint: http://192.168.213.128/stat

#日志配置
logging:
  level:
    com.ipc: DEBUG
